### ISSUE TITLE
Empty or absent configuration values (get configuration response) are not accepted

### ISSUE THREAD

**Issue by markvandenbergh** [motown-io/motown#54]
An entry in the 'get configuration' response:
```json
{"key":"config-entry","readonly":false,"value":""}
```
or
```json
{"key":"config-entry","readonly":false}
```
triggers the stack trace below

```
2015-11-26 10:42:43,460 [qtp934339113-53] ERROR i.m.o.websocketjson.OcppJsonService - Unable to handle message
java.lang.IllegalArgumentException: null
	at com.google.common.base.Preconditions.checkArgument(Preconditions.java:111) ~[guava-16.0.1.jar:na]
	at io.motown.domain.api.chargingstation.ConfigurationItem.<init>(ConfigurationItem.java:43) ~[domain-core-api-0.8.3-SNAPSHOT.jar:na]
	at io.motown.ocpp.websocketjson.response.handler.GetConfigurationResponseHandler.toConfigurationItems(GetConfigurationResponseHandler.java:55) ~[ocpp-websocket-json-0.8.3-SNAPSHOT.jar:na]
	at io.motown.ocpp.websocketjson.response.handler.GetConfigurationResponseHandler.handle(GetConfigurationResponseHandler.java:42) ~[ocpp-websocket-json-0.8.3-SNAPSHOT.jar:na]
	at io.motown.ocpp.websocketjson.OcppJsonService.handleMessage(OcppJsonService.java:84) ~[ocpp-websocket-json-0.8.3-SNAPSHOT.jar:na]
	at io.motown.ocpp.websocketjson.servlet.OcppWebSocketServlet.onTextStream(OcppWebSocketServlet.java:70) [ocpp-websocket-json-0.8.3-SNAPSHOT.jar:na]
```

According to the OCPP 1.5 SOAP and JSON spec the 'value' entry is optional, and empty strings are allowed.

```
value string[500] 0..1 Optional. If key is known but not set, this
attribute may be absent.
```

**Comment by deraaij** [comment]
Just for reference, in case of an empty string all items should be returned.

**Comment by markvandenbergh** [comment]
This is regarding the parsing of the "get configuration" response coming from the charge point.

The charge point returns a list of configuration items in response to a "get configuration" request from Motown, and if one of the values is empty or omitted the parsing fails with error mentioned above.

According to the OCPP spec the value is optional so Motown should be altered to accept empty of omitted "value" tags.
