### ISSUE TITLE
When I start a transaction, I got this error. Is there something missing?

### ISSUE THREAD

**Issue by soyoeml** [motown-io/motown#57]
Hi,

When I start a transaction, I got this error. Is there something missing? Do we need add a user or something like that? I have already sent authorize packet. In the function findSessionInfoByAuthorizationId, I don't know why it need a session info. I checked the protocol and there is no session metioned.

`2016-11-16 16:32:50,960 [qtp1057064084-41] WARN  o.a.c.callbacks.LoggingCallback - Command resulted in exception: io.motown.domain.api.chargingstation.AuthorizeCommand
javax.persistence.NoResultException: No entity found for query
	at org.hibernate.ejb.QueryImpl.getSingleResult(QueryImpl.java:286) ~[hibernate-entitymanager-4.2.2.Final.jar:4.2.2.Final]
	at io.motown.mobieurope.destination.persistence.repository.DestinationSessionRepository.findSessionInfoByAuthorizationId(DestinationSessionRepository.java:39) ~[mobi-europe-destination-0.8.3-SNAPSHOT.jar:na]
	at io.motown.mobieurope.destination.eventlisteners.TransactionStartedEventListener.onEvent(TransactionStartedEventListener.java:44) ~[mobi-europe-destination-0.8.3-SNAPSHOT.jar:na]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[na:1.8.0_91]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[na:1.8.0_91]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[na:1.8.0_91]
	at java.lang.reflect.Method.invoke(Method.java:498) ~[na:1.8.0_91]
	at org.axonframework.common.annotation.MethodMessageHandler.invoke(MethodMessageHandler.java:85) ~[axon-core-2.1.2.jar:2.1.2]
	at org.axonframework.common.annotation.MessageHandlerInvoker.invokeHandlerMethod(MessageHandlerInvoker.java:67) ~[axon-core-2.1.2.jar:2.1.2]
	at org.axonframework.eventhandling.annotation.AnnotationEventListenerAdapter.handle(AnnotationEventListenerAdapter.java:124) ~[axon-core-2.1.2.jar:2.1.2]
	at sun.reflect.GeneratedMethodAccessor53.invoke(Unknown Source) ~[na:na]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[na:1.8.0_91]
	at java.lang.reflect.Method.invoke(Method.java:498) ~[na:1.8.0_91]
	at org.axonframework.common.annotation.AbstractAnnotationHandlerBeanPostProcessor$AdapterIntroductionInterceptor.invoke(AbstractAnnotationHandlerBeanPostProcessor.java:363) [axon-core-2.1.2.jar:2.1.2]
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:179) [spring-aop-4.0.3.RELEASE.jar:4.0.3.RELEASE]
	at org.springframework.aop.framework.CglibAopProxy$DynamicAdvisedInterceptor.intercept(CglibAopProxy.java:644) [spring-aop-4.0.3.RELEASE.jar:4.0.3.RELEASE]
	at io.motown.mobieurope.destination.eventlisteners.TransactionStartedEventListener$$EnhancerBySpringCGLIB$$af8a41fd.handle(<generated>) ~[spring-core-4.0.3.RELEASE.jar:na]
	at org.axonframework.eventhandling.SimpleCluster.doPublish(SimpleCluster.java:65) ~[axon-core-2.1.2.jar:2.1.2]
	at org.axonframework.eventhandling.AbstractCluster.publish(AbstractCluster.java:77) ~[axon-core-2.1.2.jar:2.1.2]
	at org.axonframework.eventhandling.ClusteringEventBus$SimpleEventBusTerminal.publish(ClusteringEventBus.java:132) ~[axon-core-2.1.2.jar:2.1.2]
	at org.axonframework.eventhandling.ClusteringEventBus.publish(ClusteringEventBus.java:94) ~[axon-core-2.1.2.jar:2.1.2]
	at org.axonframework.unitofwork.DefaultUnitOfWork.publishEvents(DefaultUnitOfWork.java:270) ~[axon-core-2.1.2.jar:2.1.2]
	at org.axonframework.unitofwork.DefaultUnitOfWork.doCommit(DefaultUnitOfWork.java:140) ~[axon-core-2.1.2.jar:2.1.2]
	at org.axonframework.unitofwork.NestableUnitOfWork.commit(NestableUnitOfWork.java:59) ~[axon-core-2.1.2.jar:2.1.2]
	at org.axonframework.commandhandling.SimpleCommandBus.doDispatch(SimpleCommandBus.java:137) [axon-core-2.1.2.jar:2.1.2]
	at org.axonframework.commandhandling.SimpleCommandBus.doDispatch(SimpleCommandBus.java:103) [axon-core-2.1.2.jar:2.1.2]
	at org.axonframework.commandhandling.SimpleCommandBus.dispatch(SimpleCommandBus.java:70) [axon-core-2.1.2.jar:2.1.2]
	at io.motown.domain.utils.axon.EventWaitingGateway.sendAndWaitForEvent(EventWaitingGateway.java:64) [domain-utils-0.8.3-SNAPSHOT.jar:na]
	at io.motown.domain.utils.axon.EventWaitingGateway$$FastClassBySpringCGLIB$$e1882c4e.invoke(<generated>) [spring-core-4.0.3.RELEASE.jar:na]
	at org.springframework.cglib.proxy.MethodProxy.invoke(MethodProxy.java:204) [spring-core-4.0.3.RELEASE.jar:4.0.3.RELEASE]
	at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.invokeJoinpoint(CglibAopProxy.java:711) [spring-aop-4.0.3.RELEASE.jar:4.0.3.RELEASE]
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:157) [spring-aop-4.0.3.RELEASE.jar:4.0.3.RELEASE]
	at org.axonframework.common.annotation.AbstractAnnotationHandlerBeanPostProcessor$AdapterIntroductionInterceptor.invoke(AbstractAnnotationHandlerBeanPostProcessor.java:368) [axon-core-2.1.2.jar:2.1.2]
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:179) [spring-aop-4.0.3.RELEASE.jar:4.0.3.RELEASE]
	at org.springframework.aop.framework.CglibAopProxy$DynamicAdvisedInterceptor.intercept(CglibAopProxy.java:644) [spring-aop-4.0.3.RELEASE.jar:4.0.3.RELEASE]
	at io.motown.domain.utils.axon.EventWaitingGateway$$EnhancerBySpringCGLIB$$b292daf8.sendAndWaitForEvent(<generated>) [spring-core-4.0.3.RELEASE.jar:na]
	at io.motown.ocpp.viewmodel.domain.DomainService.authorize(DomainService.java:144) [ocpp-view-model-0.8.3-SNAPSHOT.jar:na]
	at io.motown.ocpp.websocketjson.request.handler.StartTransactionRequestHandler.handleRequest(StartTransactionRequestHandler.java:59) [ocpp-websocket-json-0.8.3-SNAPSHOT.jar:na]
	at io.motown.ocpp.websocketjson.OcppJsonService.processWampMessage(OcppJsonService.java:412) [ocpp-websocket-json-0.8.3-SNAPSHOT.jar:na]
	at io.motown.ocpp.websocketjson.OcppJsonService.handleMessage(OcppJsonService.java:80) [ocpp-websocket-json-0.8.3-SNAPSHOT.jar:na]
	at io.motown.ocpp.websocketjson.servlet.OcppWebSocketServlet.onTextStream(OcppWebSocketServlet.java:70) [ocpp-websocket-json-0.8.3-SNAPSHOT.jar:na]
	at org.atmosphere.websocket.DefaultWebSocketProcessor.invokeWebSocketProtocol(DefaultWebSocketProcessor.java:409) [atmosphere-runtime-2.1.3.jar:2.1.3]
	at org.atmosphere.websocket.DefaultWebSocketProcessor.invokeWebSocketProtocol(DefaultWebSocketProcessor.java:318) [atmosphere-runtime-2.1.3.jar:2.1.3]
	at org.atmosphere.container.Jetty9WebSocketHandler.onWebSocketText(Jetty9WebSocketHandler.java:77) [atmosphere-runtime-2.1.3.jar:2.1.3]
	at org.eclipse.jetty.websocket.common.events.ListenerEventDriver.onTextMessage(ListenerEventDriver.java:127) [websocket-common-9.0.4.v20130625.jar:9.0.4.v20130625]
	at org.eclipse.jetty.websocket.common.message.SimpleTextMessage.messageComplete(SimpleTextMessage.java:69) [websocket-common-9.0.4.v20130625.jar:9.0.4.v20130625]
	at org.eclipse.jetty.websocket.common.events.ListenerEventDriver.onTextFrame(ListenerEventDriver.java:119) [websocket-common-9.0.4.v20130625.jar:9.0.4.v20130625]
	at org.eclipse.jetty.websocket.common.events.EventDriver.incomingFrame(EventDriver.java:127) [websocket-common-9.0.4.v20130625.jar:9.0.4.v20130625]
	at org.eclipse.jetty.websocket.common.WebSocketSession.incomingFrame(WebSocketSession.java:312) [websocket-common-9.0.4.v20130625.jar:9.0.4.v20130625]
	at org.eclipse.jetty.websocket.common.extensions.ExtensionStack.incomingFrame(ExtensionStack.java:203) [websocket-common-9.0.4.v20130625.jar:9.0.4.v20130625]
	at org.eclipse.jetty.websocket.common.Parser.notifyFrame(Parser.java:200) [websocket-common-9.0.4.v20130625.jar:9.0.4.v20130625]
	at org.eclipse.jetty.websocket.common.Parser.parse(Parser.java:237) [websocket-common-9.0.4.v20130625.jar:9.0.4.v20130625]
	at org.eclipse.jetty.websocket.common.io.AbstractWebSocketConnection.read(AbstractWebSocketConnection.java:567) [websocket-common-9.0.4.v20130625.jar:9.0.4.v20130625]
	at org.eclipse.jetty.websocket.common.io.AbstractWebSocketConnection.onFillable(AbstractWebSocketConnection.java:475) [websocket-common-9.0.4.v20130625.jar:9.0.4.v20130625]
	at org.eclipse.jetty.io.AbstractConnection$ReadCallback.run(AbstractConnection.java:358) [jetty-io-9.0.4.v20130625.jar:9.0.4.v20130625]
	at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:601) [jetty-util-9.0.4.v20130625.jar:9.0.4.v20130625]
	at org.eclipse.jetty.util.thread.QueuedThreadPool$3.run(QueuedThreadPool.java:532) [jetty-util-9.0.4.v20130625.jar:9.0.4.v20130625]
	at java.lang.Thread.run(Thread.java:745) [na:1.8.0_91]`

**Comment by dennislaumen** [comment]
Hi @soyoeml! Could you please add the OCPP messages you're sending which result to this stack trace? This would help us reproduce the issue. Thanks in advance!

Furthermore, the concept _session_ is from the [MOBI.Europe](http://www.mobieurope.eu) specification, not the OCPP specification. If you aren't interested in MOBI.Europe I would advise you to ignore the MOBI.Europe UI and focus on the "regular" UI and functionality as this would simplify the things you're trying to do and would make it easier and more straight-forward to debug your issues. Please let us know if this helps.

**Comment by soyoeml** [comment]
Yes. You're right. Just use the regular UI.
